### ISSUE TITLE
Integration with Feedme

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [lindseydiloreto/craft-smartmap#33]
Wondering if you are planning on adding "Address (Smart Map)" to feedme as a possible import destination? When will this feature be added?

Thanks!

**Comment by lindseydiloreto** [comment]
I am indeed... @engram-design and I have chatted about it, and it's high on my radar.

I can't give you a specific ETA, but it is a high priority for me (aside from day-to-day client work). As soon as I've completed the integration, I'll let you know!

**Comment by bryantAXS** [comment]
If, say, we needed to do it ourself, to get our own client work out the door, could you point us in the right direction? :)

**Comment by lindseydiloreto** [comment]
@bryantAXS: Believe it or not, this is actually in the works as we speak. :)

@engram-design is actively creating the necessary hooks for 3rd party fieldtypes to integrate, and Smart Map is one of the main test candidates for that process. I'm guessing that both plugins will be compatible upon their next releases, which would theoretically be within the next week or so.

I apologize to @engram-design for speaking on his behalf. Hopefully I'm not making any promises that we (together) can't keep. ;)

**Comment by lindseydiloreto** [comment]
In an effort to avoid [duplicate threads](https://github.com/engram-design/FeedMe/issues/21) on the same topic, let's continue the conversation on the FeedMe repo. :thumbsup:

**Comment by bryantAXS** [comment]
Thanks guys!

**Comment by aaronbushnell** [comment]
I've gotten FeedMe to import to Smart Map correctly but it appears the entries are not getting geotagged upon import. Is there a way to geotag these on import or does each entry need to be manually geotagged?

**Comment by lindseydiloreto** [comment]
Smart Map won't automatically geocode the entries as they're being imported. Though this feature request has come up a few times since the Feed Me & Import integrations were introduced.

In the meantime, your best option is to perform the geocoding **before** importing. You'll be able to import the "Latitude" & "Longitude" values alongside the rest of your data. Here are a few geocoding services that people have used in the past:

 - https://smartystreets.com/
 - http://www.gpsvisualizer.com/geocoder/

If you're not dealing with too many entries, you could always open them one-by-one and click "Search Addresses" to quickly get the coordinates of each. Eventually, I'd like to build a bulk geocoding feature, which would allow you to get the coordinates of entries _after_ they've been imported. Can't give an ETA on that one though, probably many months away.

**Comment by aaronbushnell** [comment]
> In the meantime, your best option is to perform the geocoding before importing.

Makes sense! I'll plan on going this route. Thanks for the quick update!
